{{- if .Values.backend}}
apiVersion: v1
kind: Secret
metadata:
  name: express-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_DB_USERNAME: {{ .Values.secret.MONGO_DB_USERNAME | quote }}
  MONGO_DB_PASSWORD: {{ .Values.secret.MONGO_DB_PASSWORD | quote }}
{{- end }}
