{{- if .Values.backend}}
apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: express
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
{{- end }}

{{- if .Values.frontend}}
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
  selector:
    app: angular
{{- end }}